[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 120
startCommand = "grafana-server --homepath=/usr/share/grafana"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
