[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["monitoring/prometheus/**"]

[deploy]
healthcheckPath = "/-/healthy"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
