apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Railway private networking - use PROMETHEUS_URL env var
    url: ${PROMETHEUS_URL:-http://prometheus.railway.internal:9090}
    isDefault: true
    editable: false
