apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Railway private networking
    url: http://prometheus.railway.internal:9090
    isDefault: true
    editable: false
